name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
          architecture: 'x64'
      
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # For now let's install without secryst, as we don't necessarily need it.
      # We may need to change it once we start to depend on secryst maps.
      - run: pushd ruby && bundle install --jobs 4 --retry 3 --with jsexec --without secryst && popd

      - name: Test the Ruby package
        run: pushd ruby && bundle exec rake && popd

      - name: Test the JS package
        run: pushd js && npm install && npm run prepareMaps && npm test && popd

      - name: Publish to rubygems.org
        env:
          RUBYGEMS_API_KEY: ${{secrets.INTERSCRIPT_RUBYGEMS_API_KEY}}
        run: |
          gem install gem-release
          touch ~/.gem/credentials
          cat > ~/.gem/credentials << EOF
          ---
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          EOF
          chmod 0600 ~/.gem/credentials
          pushd ruby
          git status
          gem release
          popd
          pushd maps
          git status
          gem release
          popd
      - name: Publish to npmjs.org
        env:
          NPMJS_TOKEN: ${{secrets.INTERSCRIPT_NPM_TOKEN}}
        run: |
          pushd js
          npm config set //registry.npmjs.org/:_authToken=$NPMJS_TOKEN
          npm run prepareMaps
          npm publish
          popd

      # Let's keep it commented out for now. Please uncomment it once you are ready with
      # interscript-api to support Interscript v2.
      #
      #- name: Trigger interscript-api
      #  uses: peter-evans/repository-dispatch@v1
      #  with:
      #    token: ${{ secrets.INTERSCRIPT_CI_PAT_TOKEN }}
      #    repository: interscript/interscript-api
      #    event-type: ${{ github.repository }}
      #    client-payload: '{ "ref": "${{ github.ref }}" }'