name: test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Run specs on ${{ matrix.os }} ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ['2.6', '2.5', '2.4']
        python: ['3.8']
        experimental: [false]
        include:
          - ruby: '2.7'
            os: ubuntu-latest
            python: '3.8'
            experimental: true
          - ruby: '2.7'
            os: macos-latest
            python: '3.8'
            experimental: true
          - ruby: '2.7'
            os: windows-latest
            python: '3.8'
            experimental: true

    steps:
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@master

      - name: cache ruby gems
        uses: actions/cache@v2
        env:
          cache-name: cache-ruby-modules
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-${{ matrix.ruby }}-gems-${{ hashFiles('**/interscript.gemspec') }}
          restore-keys: |
            ${{ runner.os }}-ruby-${{ matrix.ruby }}-gems-

      - name: Install gems
        run: |
          gem install bundler -v "~> 2"
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 5

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install swig python3-setuptools

      - name: Install macos dependencies
        if: matrix.os == 'macos-latest'
        run: brew install swig

      - name: Install windows dependencies
        if: matrix.os == 'windows-latest'
        uses: nick-invision/retry@v1
        with:
          polling_interval_seconds: 5
          timeout_minutes: 5
          max_attempts: 3
          command: choco install --no-progress swig --version 4.0.1

      - uses: actions/cache@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python }}-pip
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python }}-pip

      - uses: actions/cache@v2
        if: matrix.os == 'macos-latest'
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-${{ matrix.python }}-pip
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python }}-pip

      - uses: actions/cache@v2
        if: runner.os == 'windows-latest'
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-${{ matrix.python }}-pip
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python }}-pip

      - name: Update Sequitur
        run: |
          pip3 install setuptools numpy
          pip3 install git+https://github.com/sequitur-g2p/sequitur-g2p@9b7c505

      - name: Run RSpecs
        run: |
          bundle exec parallel_split_test spec/
